### ISSUE TITLE
Bạn cho mình xin tài liệu về phần này ạ!

### ISSUE THREAD

**Issue by phungdx** [baolam/graph-attention-classification#1]

**Comment by baolam** [comment]
Hihi, xin lỗi bạn nhiều ạ. Đợi mình ngày 12 mình sẽ gửi cho tiết thêm ạ.
Mình ít rep mail:(

Vào 21:35, CN, 12 thg 6, 2022 Phung Dao ***@***.***> đã viết:

**Comment by baolam** [comment]
Nghiên cứu này của mình là nằm trong phần nghiên cứu về FGI(Feature Graph
Information) nhé, tài liệu file README nhé bạn hihi


Vào 17:58, Th 6, 8 thg 7, 2022 Nguyễn Đức Bảo Lâm ***@***.***>
đã viết:

**Comment by phungdx** [comment]
Cảm ơn bạn nhé!
